### ISSUE TITLE
[TASKS] Pilot Testing | UX Enhancement

### ISSUE THREAD

**Issue by KyleMiguelLaurente** [jedpedregosa/BespeakDevelopment#140]
- [x] Mobile No. Default *+639*
- [x]  Invalid email format probably because of the space in autocomplete feature

- [x] Modal > I'm Interested Button 
- [x] MenuTabNav Notification Badge Issue (needs to restart para mawala ung badge)
- [x] Scan Screen "Scan a bespeak QR Code" need to established text guide lang.
- [x] Preview Attending "Event is on" Button | Suggestion add alert if possible
- [x] Suggestion for "Event in Comment" will be notified organizer.
- [x] SignUp > Almost There "By clicking" | Gawing 1 line
- [x] SignUp > Sign Up as... "Card" putol description| MarginRight
- [x] SignUp > Terms and Data Policy |Uniform dapat
- [x] Event Info when matatapos ang nasa Event Card which is after 1 day after the said sched

- [x] Follow "Count" > "Array Count"
- [x] Edit Profile > DP gawing nakaibabaw kasi mahirap pindutin
- [x] SearchScreeb > Add "X" icon to clear search

**Comment by jedpedregosa** [comment]
"Invalid email format probably because of the space in autocomplete feature" 

This is invalid. Baka may case siya na may space yung email niya doon sa auto complete directory niya.

**Comment by jedpedregosa** [comment]
"Mobile No. Default +639"

Ano work around dito??

--Optional to, dagdag trabaho lang e, ang possible dito is, lagyan nung dropdownlist na may +63 tapos 9 digit nalang max sa mobile no.

**Comment by jedpedregosa** [comment]
"MenuTabNav Notification Badge Issue (needs to restart para mawala ung badge)"

Accepted narin 'to. Any enhancement na gagawin pa diyan would require decrease in app efficiency. Unless i-rerefactor pa buong code structure.

**Comment by jedpedregosa** [comment]
"Event Info when matatapos ang nasa Event Card which is after 1 day after the said sched" 

This is invalid na. Pwede mag admit kahit event ended na

**Comment by jedpedregosa** [comment]
"Suggestion for "Event in Comment" will be notified organizer."

Separated a ticket: https://github.com/jedpedregosa/BespeakDevelopment/issues/142

**Comment by jedpedregosa** [comment]
"Mobile No. Default +639"

@KyleMiguelLaurente sa'yo pala 'to ihh. Gawa kana dropdown HAHAHHA
