### ISSUE TITLE
[TASKS] Enhancements #3 

### ISSUE THREAD

**Issue by KyleMiguelLaurente** [jedpedregosa/BespeakDevelopment#17]
- [x] React Router for Profile Tabs
- [x] React Router for Active Text input (if kaya, prefer ni denise ang may active/focus textinput)

**Comment by KyleMiguelLaurente** [comment]
- [x] Profile Designs [Tabs included such as Create Event | Ticket Stub | Saved Bookmark]

**Comment by KyleMiguelLaurente** [comment]
- [x] Login In UI Enhancement [Refer to Figma]
- [x] Sign Up UI Enhancement [Refer to Figma]

**Comment by jedpedregosa** [comment]
- [x] In profile, mag lagay ng button sa baba ng change pass button na kulay puti and orange bordered for 'Log Out'.
- [x] In profile, hindi dapat nasasama sila tab buttons sa pag scroll.
- [x] Sa event view, magkadikit si Follow/Followed button sa organizer name.
- [x] Dumidikit sa right side ng pc ko yung ibang elements na nasa right.
- [x] Event cards naka dikit din sa right side.
- [x] YUNG MGA TEXTBOX BAT HINDI KATULAD NG KAY BOSS NA BORDERED
https://stackoverflow.com/questions/34087459/focus-style-for-textinput-in-react-native

**Comment by KyleMiguelLaurente** [comment]
- [x] Profile > Tabs > Content text positioning

**Comment by KyleMiguelLaurente** [comment]
- [x] Error messages and logic Log In Password
- [x] Forgot Password, Text input shrinking dunno why
- [x] Edit Profile Screen, InputStandard issue, "placeholder logic"

**Comment by jedpedregosa** [comment]
closing
